# Generated by Django 5.1.2 on 2024-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
